config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  resources :users, only: :index
    get 'users/logout', to: 'users#logout', as: 'logout'
    get 'users/check_messages_count', to: 'users#check_messages_count', as: 'check_messages_count'

  get 'messages/update_message', to: 'messages#update_message', as: 'update_message'
  get 'messages/download_messages', to: 'messages#download_messages', as: 'download_messages'  
  post 'messages/show_message', to: 'messages#show_message', as: 'show_message'
  match 'messages/find_messages', to: 'messages#find_messages', as: 'find_messages', via: [:get, :post]
  
  get "/auth/:provider/callback" => 'sessions#create'
  get "/auth/failure" => 'sessions#error'

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user

	validates_uniqueness_of :message_id

	def self.letters_search(search_params, user_id)
		u_mes = user_messages(user_id)
		result = u_mes.where('body like ? OR message_to like ? OR subject like ?',
		 "%#{search_params}%", "%#{search_params}%", "%#{search_params}%")
		result
	end

	scope :user_messages, ->(id) {where(user_id: id)}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages

	def read_user_info
		@email = self.email
		@token = self.access_token
	end

	def imap_connection
    @imap = Net::IMAP.new('imap.gmail.com', 993, usessl = true, certs = nil, verify = false)
    begin
    	@imap.authenticate('XOAUTH2', @email, @token)
    rescue => error
    	@imap.disconnect()
			logger.debug "ERROR - #{error}"
			return false
		else
			@imap.list('*', '*').each do |box|
				@mailbox_name = box.name if box.attr.include?(:Sent)
			end
			@imap.select("#{@mailbox_name}")			
			@imap
		end
	end

	def download_messages(last_update = self.last_update)
		token_expires?
		read_user_info

		if last_update
			today = Net::IMAP.format_date(last_update)
			search_params = ['SINCE', today]
		else
			search_params = ['ALL']
		end
		
		imap = imap_connection
		if imap

			imap.search(search_params).each do |message_id|				
			  msg = imap.fetch(message_id, 'RFC822')[0].attr['RFC822']
				email = Mail.new(msg)
					
				message_already_added?(email) if last_update
				email_processing(email) if !last_update			
			end

			self.update(last_update: DateTime.now.to_date)	
			imap.logout()
			imap.disconnect()	
		end		
	end

	def show_message_count
		read_user_info
		imap = imap_connection
		if imap
	    messages_count = imap.status("#{@mailbox_name}", ['MESSAGES'])['MESSAGES']
			imap.logout()
			imap.disconnect()	
			messages_count
		end
	end

	def message_already_added?(email)
		id = email.message_id
		message = Message.find_by_message_id(id)
		email_processing(email) if message.nil?
	end

	def email_processing(email)
		if email.multipart?
	    charset = email.text_part.content_type_parameters[:charset]
	    email_body = email.text_part.body.to_s.force_encoding(charset).encode("UTF-8")
		else
	    charset = email.content_type_parameters[:charset]
	    email_body = email.body.decoded.force_encoding(charset).encode("UTF-8")
		end

		self.messages.create(
			message_id: email.message_id,
			message_to: email.to.join(', '),
			subject: email.subject,
			body: email_body,
			send_date: email.date.to_s			
		)
	end
 
  def request_token_from_google
		params = {'refresh_token' => self.refresh_token,
				    	'client_id' => ENV["GOOGLE_CLIENT_ID"],
				    	'client_secret' => ENV["GOOGLE_CLIENT_SECRET"],
				    	'grant_type' => 'refresh_token'
				  	 }
    url = URI("https://accounts.google.com/o/oauth2/token")
    Net::HTTP.post_form(url, params)
  end
 
  def refresh!
    response = request_token_from_google
    data = JSON.parse(response.body)
    update_attributes(
    access_token: data['access_token'],
    expires_at: Time.now + (data['expires_in'].to_i).seconds)
  end
 
  def token_expires?
    if expires_at < Time.now
    	refresh!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	current_user ||= User.find_by_email(session[:user_email]) if session[:user_email]
  end

  def current_messages
  	current_messages = current_user.messages.page(params[:page]).per(10).order('id DESC')
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def download_messages
		Thread.new do
			current_user.download_messages
		end
		respond_to do |format|
			format.js 
			format.html {redirect_to root_path}	
		end	
	end

	def update_message
		user = current_user
		user.download_messages

		@messages = current_messages

		respond_to do |format|
			format.js 
			format.html {redirect_to root_path}	
		end		
	end

	def show_message
		user = current_user
		message = user.messages.find_by_message_id(params[:message_name])
		if message
			render json: {
				to: "#{message.message_to}",
				subject: "#{message.subject}",
				message: "#{message.body}"
			}
		else
			render json: {data: 'Not found'}
		end
	end

	def find_messages
		@messages = Message.letters_search(params[:message][:data], current_user.id)
		.page(params[:page]).per(10).order('id DESC')

		respond_to do |format|
			format.js
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false

  def index
  end

  def create
    auth = request.env["omniauth.auth"]
    session[:gmail_access_token] = auth[:credentials][:token]
    session[:user_email] = auth[:extra][:raw_info][:email]
    user = User.find_or_initialize_by(email: auth[:extra][:raw_info][:email])

    user.access_token = auth[:credentials][:token]
    user.refresh_token = auth[:credentials][:refresh_token] if auth[:credentials][:refresh_token].present?
    user.expires_at = Time.at(auth[:credentials][:expires_at]).to_datetime
    user.code = params[:code]
    user.save

    count = user.show_message_count  	

    redirect_to controller: 'users', action: 'index', mcount: "#{count}"
  end  

  def error
    render html: "<h3 style='margin-left:35%;'>Authentication failure. Please try again
     <a href=#{root_path}>Main page</a></h3>".html_safe
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
  	@user = current_user
    if @user
 		  @messages = current_messages      
    end
	end

	def logout
		session[:user_email] = nil
		session[:gmail_access_token] = nil
		redirect_to root_path
	end

	def check_messages_count
		count = current_user.messages.count
		render json: {count: "#{count}"}
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def subjects(subject)
		if subject.present?
			return subject
		else
			return 'No subject'
		end
	end

# flash messages

  def flash_class(flash_type)
    case flash_type
      when 'success'
        "alert-success" # Green
      when 'error'
        "alert-danger" # Red
      when 'alert'
        "alert-warning" # Yellow
      when 'notice'
        "alert-info" # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-dismissable <%= flash_class(key) %> fade in">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class='navbar navbar-inverse navbar-fixed-top'>
	<% if current_user %>
		<div class='search_block'>		
			<div class="row">
			  <div class="col-lg-6">
			    <div class="input-group">
			    	<%= form_for :message, url: find_messages_path, method: :post, remote: true do |f| %>
			    		<%= f.text_field :data, class: 'form-control' %>
			    		<span class="input-group-btn">
			    			<%= f.submit 'Search', name: nil, class: 'btn btn-primary' %>
			    		</span>
			    	<% end %>
			    </div>
			  </div>
			</div>
			<%= link_to update_message_path(page: params[:page]),
			 class: 'btn btn-default', id: 'refresh_btn',
			 title: "Refresh messages", type: 'button', remote: true do %>		 
				<i class="fa fa-refresh"></i>				
			<% end %>		
			<span class='messages_count'><%= current_user.messages.count %></span>
		</div>
	<% end %>

	<% if current_user %>
		<span class='user_email'> <%= current_user.email %></span>
		<div class='user_controll_block'>
			<%= link_to 'Log out', logout_path, class: 'btn btn-primary logout_btn' %>
		</div>
	<% else %>
		<%= link_to 'Authenticate with GMail!', '/auth/google_oauth2',
		 class: 'btn btn-primary btn-lg auth_btn' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sendmailviewer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= render 'layouts/flash_messages' %>

	<%= yield %>

	<%= yield :after_body %>

</body>
</html>

app/views/messages/find_messages.js.erb
var table = $('.table_container .table');
table.find('tr:not(".col_title")').remove();
table.append("<%= j render partial: 'users/message', collection: @messages %>");
$('.table_container td b, .table_container td p, .table_container td br')
.addClass('linear_body');

$('.pagination_block')
.html("<%= j paginate(@messages, left: 3, right: 3, remote: true) %>");

app/views/messages/update_message.js.erb
var table = $('.table_container .table');
table.find('tr:not(".col_title")').remove();
table.append("<%= j render partial: 'users/message', collection: @messages %>");
$('.table_container td b, .table_container td p, .table_container td br')
.addClass('linear_body');

var count = <%= current_user.messages.count %>
$('.messages_count').text(count);

$('.pagination_block')
.html("<%= j paginate(@messages, params: {controller: 'users', action: 'index'},\
 left: 3, right: 3, remote: true) %>");

$('#refresh_btn').attr('disabled',false);
$('.pagination').show();
$('.progress_block').css('display', 'none');

flash_message('Messages successfully updated');

app/views/users/_message.html.erb
<tr class='message_info_view' data-name = <%= message.message_id %> >			
	<td><%= 1 %></td>
	<td><%= message.send_date.strftime("%A, %d %B %Y, %H:%M") %></td>
	<td><%= message.message_to %></td>
	<td>
		<b><%= subjects(message.subject) %> : </b><%= truncate_html(message.body, length: 100, omission: '...') %>
	</td>
</tr>

app/views/users/index.html.erb
<% if @user %>
	<div class='table_container table-responsive'>
		<div class='pagination_block'>
			<%= paginate @messages, left: 3, right: 3, remote: true %>
		</div>
		<div class='progress_block'>
			<div class='mail_progress_bar'>
				<div class="progress progress-striped active">
				  <div class="progress-bar"  role="progressbar" aria-valuenow="100"
				   aria-valuemin="0" aria-valuemax="100" style="width: 100%">
				    <span class="sr-only">45% Complete</span>
				  </div>
				</div>
			</div>
		</div>
		<table class="table table-hover">
			<tr class='col_title'>
				<td class='message_id'>#</td>
				<td class='message_date'>Date</td>
				<td class='message_to'>Message to</td>
				<td class='message_body'>Content</td>
			</tr>
			<%= render partial: 'message', collection: @messages %>
		</table>
	</div>

	<div id="message">
		<div id="message_full_body">
			<div id="message_close" title="Close message" onclick='message_close()'>
				<i class="fa fa-times"></i>
			</div>
			<div id="mf_subject">
				<span>Subject:</span>
				<span>No Subject</span>
			</div>
			<div id="mf_to">
				<span>To:</span>
				<span>Empty</span>
			</div>
			<div id="mf_body">
				<span>Empty</span>
			</div>
		</div>	
	</div>
	
<% end %>

<% content_for :after_body do %>
	<%= javascript_include_tag 'for_views/index.js' %>
<% end %>

app/views/users/index.js.erb
var table = $('.table_container .table');
table.find('tr:not(".col_title")').remove();
table.append("<%= j render partial: 'message', collection: @messages %>");
$('.table_container td b, .table_container td p, .table_container td br')
.addClass('linear_body');

$('.pagination_block')
.html("<%= j paginate(@messages, left: 3, right: 3, remote: true) %>");

var page = parseInt($('.pagination_block .current').text());
btn = $('#refresh_btn');
url = "/messages/update_message/?page="+page;
url = btn.attr('href', url);